### PR TITLE
Small fix for semi_join() and anti_join(): always end with data.frame, not a vector

### PR DESCRIPTION
**Pull request by msberends**

### CODE REVIEW

**Comment by msberends** [comment]
You might check all of your code for `x[y, z]` and `x[y, ]` cases, and replace them with `x[y, z, drop = FALSE]` and `x[y, , drop = FALSE]` to prevent that you will end up with a vector if `z` has length one.

**Comment by nathaneastwood** [comment]
Hey thanks for the PR! Do you have a working example for this at all? I agree that this is a needed fix, I just want to add some tests as well so it doesn't somehow get reintroduced in the future.

Also, I updated master so in future PRs will refer you to the [git commit standards](https://github.com/nathaneastwood/poorman/blob/master/.github/contributing.md#-git-commit-standards) for the project.

**Comment by msberends** [comment]
Yes, I ran into trouble using an anti join last week. I’ll look it up!

**Comment by msberends** [comment]
Here it is:

```r
tbl1 <- data.frame(a = sample(rep(LETTERS[1:3], 10)), 
                   stringsAsFactors = FALSE)
tbl2 <- data.frame(a = LETTERS[1:3],
                   b = colours()[1:3], 
                   stringsAsFactors = FALSE)

class(poorman::semi_join(tbl1, tbl2))
#> [1] "character"
class(dplyr::semi_join(tbl1, tbl2))
#> [1] "data.frame"
```

**Pull request merged**
